spring:
  application:
    name: "gateway-server"
  cloud:
    gateway:
      mvc:
        routes:
          - id: "order-service"
            uri: "http://localhost:8081"
            predicates:
              - "Path=/api/v1/order/**"
          - id: "product-service"
            uri: "http://localhost:8085"
            predicates:
              - "Path=/api/v1/product/**"
          - id: "cart-service"
            uri: "http://localhost:8082"
            predicates:
              - "Path=/api/v1/cart/**"
          - id: "customer-service"
            uri: "http://localhost:8086"
            predicates:
              - "Path=/api/v1/customer/**"
          - id: "identity-service"
            uri: "http://localhost:8083"
            predicates:
              - "Path=/api/v1/identity/**"
          - id: "notification-service"
            uri: "http://localhost:8084"
            predicates:
              - "Path=/api/v1/notification/**"

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true