spring:
  application:
    name: "identity-service"
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka"
    register-with-eureka: true
    fetch-registry: true