spring:
  application:
    name: "order-service"
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081