spring:
  application:
    name: "product-service"
  data:
    mongodb:
      uri: mongodb://admin:test@localhost:27017/admin
      database: mydatabase

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka"
    register-with-eureka: true
    fetch-registry: true



