spring:
  application:
    name: "cart-service"
  data:
    mongodb:
      uri: mongodb://admin:test@localhost:27018/admin
      database: mydatabase

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true